from studiosr.models.edsr import EDSR
from studiosr.models.espcn import ESPCN
from studiosr.models.han import HAN
from studiosr.models.hat import HAT
from studiosr.models.maxsr import MaxSR
from studiosr.models.rcan import RCAN
from studiosr.models.srcnn import SRCNN
from studiosr.models.srresnet import SRResNet
from studiosr.models.swinfir import SwinFIR
from studiosr.models.swinir import SwinIR
from studiosr.models.vdsr import VDSR
